export const articoli = [
    {
        slug: 'articolo-1',
        id: 1,
        data: 'Data di pubblicazione',
        titolo: 'Titolo dell\'articolo o comunicato ufficiale',
        estratto: 'Estratto o breve descrizione del contenuto dell\'articolo, per invogliare il lettore a cliccare e leggere di più.',
        img: '/images/news-1.jpg',
        tag: 'Evento',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Testo introduttivo dell\'articolo' },
            { tipo: 'titolo', testo: 'Titolo paragrafo interno' },
            { tipo: 'paragrafo', testo: 'Secondo paragrafo dell\'articolo' },
            { tipo: 'paragrafo', testo: 'Terzo paragrafo dell\'articolo' },
        ],
    },
    {
        slug: 'articolo-2',
        id: 2,
        data: 'Data di pubblicazione',
        titolo: 'Titolo dell\'articolo o comunicato ufficiale',
        estratto: 'Estratto o breve descrizione del contenuto dell\'articolo, per invogliare il lettore a cliccare e leggere di più.',
        img: '/images/news-2.jpg',
        tag: 'Comunicato',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Testo introduttivo dell\'articolo' },
            { tipo: 'titolo', testo: 'Titolo paragrafo interno' },
            { tipo: 'paragrafo', testo: 'Secondo paragrafo dell\'articolo' },
        ],
    },
    {
        slug: 'articolo-3',
        id: 3,
        data: 'Data di pubblicazione',
        titolo: 'Titolo dell\'articolo o comunicato ufficiale',
        estratto: 'Estratto o breve descrizione del contenuto dell\'articolo, per invogliare il lettore a cliccare e leggere di più.',
        img: '/images/news-3.jpg',
        tag: 'Regolamento',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Testo introduttivo dell\'articolo' },
            { tipo: 'titolo', testo: 'Titolo paragrafo interno' },
            { tipo: 'paragrafo', testo: 'Secondo paragrafo dell\'articolo' },
        ],
    },
    {
        slug: 'articolo-4',
        id: 4,
        data: 'Data di pubblicazione',
        titolo: 'Titolo dell\'articolo o comunicato ufficiale',
        estratto: 'Estratto o breve descrizione del contenuto dell\'articolo, per invogliare il lettore a cliccare e leggere di più.',
        img: '/images/news-4.jpg',
        tag: 'Guida',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Testo introduttivo dell\'articolo' },
            { tipo: 'titolo', testo: 'Titolo paragrafo interno' },
            { tipo: 'paragrafo', testo: 'Secondo paragrafo dell\'articolo' },
        ],
    },
]

export const eventi = [
    {
        slug: 'evento-1',
        id: 1,
        data: 'Data di svolgimento',
        luogo: 'Luogo di svolgimento',
        titolo: 'Titolo dell\'evento',
        desc: 'Descrizione breve dell\'evento.',
        tag: 'Evento Nazionale',
        stato: 'upcoming',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Descrizione completa dell\'evento' },
            { tipo: 'titolo', testo: 'Come partecipare' },
            { tipo: 'paragrafo', testo: 'Informazioni su iscrizioni e modalità di partecipazione' },
            { tipo: 'titolo', testo: 'Attrezzatura richiesta' },
            { tipo: 'paragrafo', testo: 'Lista attrezzatura obbligatoria' },
        ],
        info: [
            { label: 'Data', valore: 'Data di svolgimento' },
            { label: 'Luogo', valore: 'Luogo di svolgimento' },
            { label: 'Divisioni', valore: 'Rookie, Standard, Open' },
            { label: 'Iscrizioni', valore: 'Aperte' },
            { label: 'Posti disponibili', valore: 'Da definire' },
        ],
    },
    {
        slug: 'evento-2',
        id: 2,
        data: 'Data di svolgimento',
        luogo: 'Luogo di svolgimento',
        titolo: 'Titolo dell\'evento',
        desc: 'Descrizione breve dell\'evento.',
        tag: 'Evento Regionale',
        stato: 'upcoming',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Descrizione completa dell\'evento' },
            { tipo: 'titolo', testo: 'Come partecipare' },
            { tipo: 'paragrafo', testo: 'Informazioni su iscrizioni e modalità di partecipazione' },
        ],
        info: [
            { label: 'Data', valore: 'Data di svolgimento' },
            { label: 'Luogo', valore: 'Luogo di svolgimento' },
            { label: 'Divisioni', valore: 'Rookie, Standard, Open' },
            { label: 'Iscrizioni', valore: 'Aperte' },
            { label: 'Posti disponibili', valore: 'Da definire' },
        ],
    },
    {
        slug: 'evento-3',
        id: 3,
        data: 'Data di svolgimento',
        luogo: 'Luogo di svolgimento',
        titolo: 'Titolo dell\'evento',
        desc: 'Descrizione breve dell\'evento.',
        tag: 'Evento Regionale',
        stato: 'upcoming',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Descrizione completa dell\'evento' },
            { tipo: 'titolo', testo: 'Come partecipare' },
            { tipo: 'paragrafo', testo: 'Informazioni su iscrizioni e modalità di partecipazione' },
        ],
        info: [
            { label: 'Data', valore: 'Data di svolgimento' },
            { label: 'Luogo', valore: 'Luogo di svolgimento' },
            { label: 'Divisioni', valore: 'Rookie, Standard, Open' },
            { label: 'Iscrizioni', valore: 'Aperte' },
            { label: 'Posti disponibili', valore: 'Da definire' },
        ],
    },
    {
        slug: 'evento-4',
        id: 4,
        data: 'Data di svolgimento',
        luogo: 'Luogo di svolgimento',
        titolo: 'Titolo dell\'evento',
        desc: 'Descrizione breve dell\'evento.',
        tag: 'Campionato',
        stato: 'upcoming',
        contenuto: [
            { tipo: 'paragrafo', testo: 'Descrizione completa dell\'evento' },
            { tipo: 'titolo', testo: 'Come qualificarsi' },
            { tipo: 'paragrafo', testo: 'Informazioni sulle qualificazioni' },
        ],
        info: [
            { label: 'Data', valore: 'Data di svolgimento' },
            { label: 'Luogo', valore: 'Luogo di svolgimento' },
            { label: 'Accesso', valore: 'Solo atleti qualificati' },
            { label: 'Iscrizioni', valore: 'Su qualificazione' },
            { label: 'Posti disponibili', valore: 'Da definire' },
        ],
    },
]